### ISSUE TITLE
Data download not working

### ISSUE THREAD

**Issue by fuxuliu** [THUDM/ProteinLM#7]
It seems like the data download is not working.

For example:
wget http://s3.amazonaws.com/proteindata/data_pytorch/pfam.tar.gz
 terminates with a HTTP 403：Forbidden

and the other data is the same.

**Comment by Yijia-Xiao** [comment]
Hi @Gary-Deeplearning:

Thank you for the feedback. I have updated the download address of the datasets. If there is any other problems, please feel free to contact me.

Best,
Yijia Xiao
